# Generated by Django 3.0 on 2021-12-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivosonu', '0002_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posteo',
        ),
    ]
