# Generated by Django 3.0 on 2021-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivosonu', '0004_auto_20211215_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
